services:
  web:
    image: princewillopah/django-app1-web:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - staticfiles:/app/staticfiles
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  staticfiles:
  postgres_data:

networks:
  app-network:
    driver: bridge




# services:
#         web:
#           build: .
#           ports:
#             - "8000:8000"
#           env_file:
#             - .env
#           depends_on:
#             - db
#           volumes:
#             - staticfiles:/app/staticfiles
#           networks:
#             - app-network

#         db:
#           image: postgres:13
#           environment:
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: postgres
#             POSTGRES_DB: myproject
#           volumes:
#             - postgres_data:/var/lib/postgresql/data
#           networks:
#             - app-network

# volumes:
#   staticfiles:
#   postgres_data:

# networks:
#   app-network:
#     driver: bridge